### ISSUE TITLE
move-file only supports node >= 10.17

### ISSUE THREAD

**Issue by ro-savage** [sindresorhus/move-file#10]
Hi,

`move-file` is breaking dependencies upstream because it required node 10.17.
While other packages believe they only need node 10.x

For example:
https://github.com/npm/cacache/issues/37
https://github.com/webpack-contrib/compression-webpack-plugin/issues/165

Does this package really need node 10.17? A quick glance as the code looks like it would work on all 10.x versions of node?

**Comment by artemirq** [comment]
The same issue, it's breaks [my CI tests](https://github.com/artemirq/zero-scriptsjs/pull/574/checks?check_run_id=694652080)

**Comment by tillcarlos** [comment]
Same issue. It's coming with `"@rails/webpacker@5.0.1"` (via cacacher), and thus breaks on [heroku](https://devcenter.heroku.com/changelog-items/1657) 

Heroku: "Ruby apps now default to Node version 10.15.3 and Yarn version 1.16.0"

**Comment by deviantfero** [comment]
This issue is also affecting `copy-webpack-plugin`

**Comment by evilebottnawi** [comment]
/cc @sindresorhus I know the package has engine field with node https://github.com/sindresorhus/move-file/blob/master/package.json#L14, but a lot of packages do not use same node version in their `package.json`, for example - https://github.com/npm/cacache/blob/latest/package.json#L93. 

A lot of developers use yarn and here generates an error when the node version is not suitable. npm generates an annoying warning. Other developers have problems with CI.

Are you ready to downgrade node version to `10.13`? I can send a PR using `util.promisify` when node is not supported `fs.promise`.

**Comment by sindresorhus** [comment]
> move-file is breaking dependencies upstream because it required node 10.17.
While other packages believe they only need node 10.x

Ugh. There's no winning this: https://github.com/sindresorhus/meta/issues/8 ...

**Comment by sindresorhus** [comment]
Also see https://github.com/sindresorhus/move-file/commit/9153d5b6a0cce729049161014323feb05a87c63f#commitcomment-39613575

**Comment by sindresorhus** [comment]
> Are you ready to downgrade node version to 10.13?

Why 10.13?

> I can send a PR using util.promisify when node is not supported fs.promise.

Sure

**Comment by sokra** [comment]
> Why 10.13?

I think that's the first LTS node 10 release

**Comment by sindresorhus** [comment]
Closing as this package now targets Node.js 12, so this is no longer relevant.

https://github.com/sindresorhus/move-file/releases/tag/v3.0.0
