### ISSUE TITLE
Add `directoryMode` option

### ISSUE THREAD

**Issue by dittyroma** [sindresorhus/move-file#13]
The module functions offer no way to specify mode for implicitly created directories so they always create directories world writable. If a user wants to ensure secure directories they have to avoid these methods. Accepting a directory mode would make it possible to use them securely.

World writable resources such as config files can allow other users to control program behavior. In some cases there's code injection through the config file, which can lead to privilege elevation. World writable directories have the same weakness since they allow adding files within them. A world writable config directory `/etc/froznator/conf.d` offers a route to controlling program behavior through a new config file. On Linux the umask should usually prevent this but it's not guaranteed. [Secure coding standards](https://wiki.sei.cmu.edu/confluence/display/c/FIO06-C.+Create+files+with+appropriate+access+permissions) recommend always specifying a restricted mode so files and directories are secure in any environment. MITRE calls this [CWE-732](https://cwe.mitre.org/data/definitions/732.html), one of the [top 25 most dangerous](https://cwe.mitre.org/top25/archive/2020/2020_cwe_top25.html) vulnerabilities.

These lines always use `mkdir` `mkdirSync` without a mode. If you used `move-file` to eg install default config files, you could end up with a world writable config directory.
https://github.com/sindresorhus/move-file/blob/bbabd081116d02363b95d01c82bcb9d9dea40e2a/index.js#L22
https://github.com/sindresorhus/move-file/blob/bbabd081116d02363b95d01c82bcb9d9dea40e2a/index.js#L50

I have reports for a couple of your other projects but I'll wait for your thoughts before peppering you with them.

This came out of research with CodeQL.

**Comment by sindresorhus** [comment]
I'm happy to have a `directoryMode` option added, but I don't see this as a big problem. I don't know of any tool that writes config to a global location, and I don't know why any tool would.

**Comment by dittyroma** [comment]
Thanks @sindresorhus. I'm going to come up with a patch to propose.
