### ISSUE TITLE
Support for commonjs modules

### ISSUE THREAD

**Issue by euberdeveloper** [sindresorhus/move-file#15]
Hi, when I updated to the new version 3, my code stopped running because it does not provide a commonjs module.

I think this is why I am using typescript, that converts import to require. (the error is `Error [ERR_REQUIRE_ESM]: Must use import to load ES Module:`)

I know that it is possible to provide both a cjs and an esm module package on npm, could be a way to add extensive support to `move-file`?

**Comment by Dijir** [comment]
it should be supported on commonjs. same issue here too
