### ISSUE TITLE
fails to transpile under ES

### ISSUE THREAD

**Issue by geetee24** [sindresorhus/move-file#20]
Error [ERR_REQUIRE_ESM]: require() of ES Module C:\GtSource\NodeJs\awsClipboard\node_modules\move-file\index.js from xxx.ts not supported.
Instead change the require of index.js in xxx.ts to a dynamic import() which is available in all CommonJS modules.
    at Module.m._compile (C:\GtSource\NodeJs\awsClipboard\node_modules\ts-node\dist\index.js:791:29)

latest version wont execute.

**Comment by sindresorhus** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
