### ISSUE TITLE
Add a convenience method for renaming a file in a directory

### ISSUE THREAD

**Issue by tommy-mitchell** [sindresorhus/move-file#22]
Given a path to a directory, it's a little cumbersome to rename a single file:

```js
import {moveFile} from 'move-file';
await moveFile(`${directoryPath}/unicorn.png`, `${directoryPath}/unicorns.png`);

// or

import fs from 'node:fs/promises';
await fs.rename(`${directoryPath}/unicorn.png`, `${directoryPath}/unicorns.png`);
```

This only gets noisier if using `path.resolve`, and the actual change can get lost or accidentally replaced.

Consider (with a `cwd` option like `cpy` or `del`):

```js
import {renameFile} from 'move-file';
await renameFile('unicorn.png', 'unicorns.png', {cwd: directoryPath});
```

**Comment by sindresorhus** [comment]
Sounds useful 👍

**Comment by sindresorhus** [comment]
I think it should allow absolute paths too as long as they both are in the same directory.
