### ISSUE TITLE
Use glob for match file name to move

### ISSUE THREAD

**Issue by am** [sindresorhus/move-file#3]
I would like to move a file which I don't have the full qualified name, like `vendor*`.

This is possible using [cpy](https://github.com/sindresorhus/cpy) but I wish to move not copy. `cpy` does not provide a delete option. 

This could be done using [globby](https://github.com/sindresorhus/globby) and then pass the path to `move-file`.

Do you think it would be helpful to add here the option to use globs?

**Comment by sindresorhus** [comment]
Thanks for the suggestion, but I don't want to complicate this package with globbing.
