### ISSUE TITLE
How do I do to move across devices? 

### ISSUE THREAD

**Issue by MarcosVRSDev** [sindresorhus/move-file#9]
I'm trying to move a file to my smartphone, but despite the returning of success, the file is not found in the informed directory on the code. Do you have any tricks to perform this operation?

Follow the code: 

```js
(async () => {
    await moveFile(
      "./arquivos/home/teste.txt",
      "Este Computador/MI 8 Lite/Armazenamento interno compartilhado/end/teste.txt"
    );
    console.log("The file has been moved");
  })();
```

**Comment by sindresorhus** [comment]
Both of these paths refer to the same drive/device. I think you're using an incorrect destination path.
